/* ==============================================================
   CONFIG — generated by admin.html on 8/27/2026, 1:02:23 PM.
   Replace the old config.js in your project with this file, then
   re-deploy your site (push to GitHub / re-upload to your host) so
   everyone sees the update.
   ============================================================== */

const CONFIG = {
  "adminPassword": "Rakhi2026",
  "ngo": {
    "enabled": true,
    "name": "GiveIndia",
    "message": "I know you don't want money directly, so I would request you to help others to whom it's more needed at this time.",
    "url": "https://www.giveindia.org/",
    "buttonText": "Donate to GiveIndia instead 🤝"
  },
  "profiles": {
    "shweta": {
      "recipientName": "Shweta",
      "revealMessage": "This one's yours — with all my love.",
      "upiId": "8623842924@superyes",
      "payeeName": "Your Name",
      "amount": 500,
      "notifyWhatsAppNumber": "",
      "notifyMessage": "I’ve successfully completed the Rakhi quiz! 😎🎊\nHappy Raksha Bandhan! 🥰🪢\nNow, where’s my Shagun? 😂💰",
      "siteUrl": "",
      "shareMessage": "I made something just for you 💛 Open this:",
      "questions": [
        {
          "text": "What's my favourite way to spend a weekend?",
          "options": [
            "Sleeping in",
            "Outdoors",
            "Something else"
          ]
        }
      ]
    },
    "meghana": {
      "recipientName": "Meghana",
      "revealMessage": "This one's yours — with all my love.",
      "upiId": "8623842924@superyes",
      "payeeName": "Your Name",
      "amount": 500,
      "notifyWhatsAppNumber": "",
      "notifyMessage": "I’ve successfully completed the Rakhi quiz! 😎🎊\nHappy Raksha Bandhan! 🥰🪢\nNow, where’s my Shagun? 😂💰",
      "siteUrl": "",
      "shareMessage": "I made something just for you 💛 Open this:",
      "questions": [
        {
          "text": "What's my favourite way to spend a weekend?",
          "options": [
            "Sleeping in",
            "Outdoors",
            "Something else"
          ]
        }
      ]
    },
    "aishwarya": {
      "recipientName": "Aishwarya",
      "revealMessage": "This one's yours — with all my love.",
      "upiId": "8623842924@superyes",
      "payeeName": "Your Name",
      "amount": 500,
      "notifyWhatsAppNumber": "",
      "notifyMessage": "I’ve successfully completed the Rakhi quiz! 😎🎊\nHappy Raksha Bandhan! 🥰🪢\nNow, where’s my Shagun? 😂💰",
      "siteUrl": "",
      "shareMessage": "I made something just for you 💛 Open this:",
      "questions": [
        {
          "text": "What's my favourite way to spend a weekend?",
          "options": [
            "Sleeping in",
            "Outdoors",
            "Something else"
          ]
        }
      ]
    },
    "pranjali": {
      "recipientName": "Pranjali",
      "revealMessage": "This one's yours — with all my love.",
      "upiId": "8623842924@superyes",
      "payeeName": "Your Name",
      "amount": 500,
      "notifyWhatsAppNumber": "",
      "notifyMessage": "I’ve successfully completed the Rakhi quiz! 😎🎊\nHappy Raksha Bandhan! 🥰🪢\nNow, where’s my Shagun? 😂💰",
      "siteUrl": "",
      "shareMessage": "I made something just for you 💛 Open this:",
      "questions": [
        {
          "text": "What's my favourite way to spend a weekend?",
          "options": [
            "Sleeping in",
            "Outdoors",
            "Something else"
          ]
        }
      ]
    },
    "prajkta": {
      "recipientName": "Prajkta",
      "revealMessage": "This one's yours — with all my love.",
      "upiId": "8623842924@superyes",
      "payeeName": "Your Name",
      "amount": 500,
      "notifyWhatsAppNumber": "",
      "notifyMessage": "I’ve successfully completed the Rakhi quiz! 😎🎊\nHappy Raksha Bandhan! 🥰🪢\nNow, where’s my Shagun? 😂💰",
      "siteUrl": "",
      "shareMessage": "I made something just for you 💛 Open this:",
      "questions": [
        {
          "text": "What's my favourite way to spend a weekend?",
          "options": [
            "Sleeping in",
            "Outdoors",
            "Something else"
          ]
        }
      ]
    }
  }
};
