/* ==============================================================
   DATA HELPERS — shared by index.html and admin.html.
   You should not need to edit this file.

   How editing actually works on a site with no server:
   - config.js is the file that's "live" for everyone who visits.
   - admin.html lets you edit things through a form. Those edits
     are saved in THIS BROWSER's storage (localStorage) so you can
     immediately preview them here.
   - To make an edit visible to everyone (including your sister on
     her own phone), use the "Download config.js" button in
     admin.html, then replace config.js in your project files and
     re-deploy the site. That's the only "publish" step.
   ============================================================== */

const RB_STORAGE_KEY = "rakshabandhan_admin_overrides_v1";

function rbLoadOverrides() {
  try {
    const raw = localStorage.getItem(RB_STORAGE_KEY);
    if (!raw) return { adminPassword: null, ngo: null, profiles: {}, deletedProfiles: [] };
    const parsed = JSON.parse(raw);
    return {
      adminPassword: parsed.adminPassword || null,
      ngo: parsed.ngo || null,
      profiles: parsed.profiles || {},
      deletedProfiles: parsed.deletedProfiles || [],
    };
  } catch (e) {
    console.error("Could not read saved admin edits:", e);
    return { adminPassword: null, ngo: null, profiles: {}, deletedProfiles: [] };
  }
}

function rbSaveOverrides(overrides) {
  try {
    localStorage.setItem(RB_STORAGE_KEY, JSON.stringify(overrides));
    return true;
  } catch (e) {
    console.error("Could not save admin edits:", e);
    return false;
  }
}

// Merges config.js (CONFIG) with anything saved via the admin dashboard
// in this browser. Overrides always win.
function rbGetEffectiveData() {
  const base = (typeof CONFIG !== "undefined") ? CONFIG : { adminPassword: "", ngo: {}, profiles: {} };
  const overrides = rbLoadOverrides();

  const mergedProfiles = Object.assign({}, base.profiles || {}, overrides.profiles || {});
  (overrides.deletedProfiles || []).forEach((key) => {
    delete mergedProfiles[key];
  });

  return {
    adminPassword: overrides.adminPassword || base.adminPassword,
    ngo: overrides.ngo || base.ngo || { enabled: false },
    profiles: mergedProfiles,
  };
}

// Returns the profile to use for the current visit, based on the
// ?to=<key> URL parameter, falling back to "default".
function rbGetActiveProfile() {
  const data = rbGetEffectiveData();
  const params = new URLSearchParams(window.location.search);
  const requested = params.get("to");
  if (requested && data.profiles[requested]) {
    return { key: requested, profile: data.profiles[requested], ngo: data.ngo };
  }
  return { key: "default", profile: data.profiles.default, ngo: data.ngo };
}

// Builds a fresh config.js file (as text) from the current effective
// data, so the user can download it and replace the one on their site.
function rbExportConfigJsText() {
  const data = rbGetEffectiveData();
  const body = {
    adminPassword: data.adminPassword,
    ngo: data.ngo,
    profiles: data.profiles,
  };
  const json = JSON.stringify(body, null, 2);
  return `/* ==============================================================
   CONFIG — generated by admin.html on ${new Date().toLocaleString()}.
   Replace the old config.js in your project with this file, then
   re-deploy your site (push to GitHub / re-upload to your host) so
   everyone sees the update.
   ============================================================== */

const CONFIG = ${json};
`;
}

function rbDownloadTextFile(filename, text) {
  const blob = new Blob([text], { type: "text/javascript" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
